### ISSUE TITLE
About ValueError

### ISSUE THREAD

**Issue by 7unahan** [jeremy43/Private_kNN#6]
First of all, it is excellent work!
There is a size problem in the code like this: 
ValueError: the input array must have size 3 along `channel_axis`, got (28, 28)

I should convert rgb to gray but where?

**Comment by 7unahan** [comment]
I convert line 123 in ultis like this:
for i in data:
      if i.shape[-1] == 3:
          train_gray = color.rgb2gray(i)
But now I have "UnboundLocalError: local variable 'train_gray' referenced before assignment"

**Comment by jeremy43** [comment]
Hi!
Could you please provide more details on which line of the code?
Regarding where to convert rgb to gray, you could find the `save_hog' function in utily.py  train_gray = [color.rgb2gray(i) for i in data]
  hog_data = [hog(img, orientations=8, block_norm='L2') for img in train_gray]

**Comment by 7unahan** [comment]
I changed this row "train_gray = [color.rgb2gray(i) for i in data]" like "train_gray = [i for i in data]" in utils.py (row 123) and passed this error on Spyder but because of the GPU problem, I transport my codes in Colab and when I try it gives me this error:


```
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/gdrive/MyDrive/Colab Notebooks/private-knn/Private_kNN-master/digit_pytorch/dataset_loader.py", line 42, in __getitem__
    img = self.transform(cur_img)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py", line 227, in __call__
    return F.to_pil_image(pic, self.mode)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional.py", line 259, in to_pil_image
    raise TypeError(f"pic should be Tensor or ndarray. Got {type(pic)}.")
TypeError: pic should be Tensor or ndarray. Got <class 'PIL.Image.Image'>.
```

<img width="930" alt="hata" src="https://user-images.githubusercontent.com/16180740/222412820-4cf3def5-028b-4270-9fc2-07bb9dababbf.png">
